# Generated by Django 5.2.4 on 2025-08-07 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_service_icon_alter_about_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='icon',
            new_name='icon_class',
        ),
    ]
