# Generated by Django 5.2.4 on 2025-08-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_service_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, null=True)),
                ('name', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(help_text='height: 1178 px width: 1775 px', null=True, upload_to='about_images/'),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(help_text='height: 1180 px width: 1770 px', null=True, upload_to='home_images/'),
        ),
    ]
