# Generated by Django 5.2.4 on 2025-08-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_client_alter_about_image_alter_home_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, null=True)),
                ('description', models.TextField(max_length=100, null=True)),
                ('image', models.ImageField(help_text='height: 1178 px width: 1775 px', null=True, upload_to='feature_images/')),
            ],
        ),
    ]
