# Generated by Django 5.2.4 on 2025-08-07 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='home',
            name='image',
        ),
    ]
